# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dishant/Desktop/travel-guide-bot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dishant/Desktop/travel-guide-bot/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dishant/Desktop/travel-guide-bot/build/CMakeFiles /home/dishant/Desktop/travel-guide-bot/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dishant/Desktop/travel-guide-bot/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named travel_guide_bot

# Build rule for target.
travel_guide_bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 travel_guide_bot
.PHONY : travel_guide_bot

# fast build rule for target.
travel_guide_bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/build
.PHONY : travel_guide_bot/fast

src/bot_logic.o: src/bot_logic.cpp.o
.PHONY : src/bot_logic.o

# target to build an object file
src/bot_logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/bot_logic.cpp.o
.PHONY : src/bot_logic.cpp.o

src/bot_logic.i: src/bot_logic.cpp.i
.PHONY : src/bot_logic.i

# target to preprocess a source file
src/bot_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/bot_logic.cpp.i
.PHONY : src/bot_logic.cpp.i

src/bot_logic.s: src/bot_logic.cpp.s
.PHONY : src/bot_logic.s

# target to generate assembly for a file
src/bot_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/bot_logic.cpp.s
.PHONY : src/bot_logic.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pathfinding.o: src/pathfinding.cpp.o
.PHONY : src/pathfinding.o

# target to build an object file
src/pathfinding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/pathfinding.cpp.o
.PHONY : src/pathfinding.cpp.o

src/pathfinding.i: src/pathfinding.cpp.i
.PHONY : src/pathfinding.i

# target to preprocess a source file
src/pathfinding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/pathfinding.cpp.i
.PHONY : src/pathfinding.cpp.i

src/pathfinding.s: src/pathfinding.cpp.s
.PHONY : src/pathfinding.s

# target to generate assembly for a file
src/pathfinding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/pathfinding.cpp.s
.PHONY : src/pathfinding.cpp.s

src/telegram_bot.o: src/telegram_bot.cpp.o
.PHONY : src/telegram_bot.o

# target to build an object file
src/telegram_bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/telegram_bot.cpp.o
.PHONY : src/telegram_bot.cpp.o

src/telegram_bot.i: src/telegram_bot.cpp.i
.PHONY : src/telegram_bot.i

# target to preprocess a source file
src/telegram_bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/telegram_bot.cpp.i
.PHONY : src/telegram_bot.cpp.i

src/telegram_bot.s: src/telegram_bot.cpp.s
.PHONY : src/telegram_bot.s

# target to generate assembly for a file
src/telegram_bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/travel_guide_bot.dir/build.make CMakeFiles/travel_guide_bot.dir/src/telegram_bot.cpp.s
.PHONY : src/telegram_bot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... travel_guide_bot"
	@echo "... src/bot_logic.o"
	@echo "... src/bot_logic.i"
	@echo "... src/bot_logic.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pathfinding.o"
	@echo "... src/pathfinding.i"
	@echo "... src/pathfinding.s"
	@echo "... src/telegram_bot.o"
	@echo "... src/telegram_bot.i"
	@echo "... src/telegram_bot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

